### ISSUE TITLE
add walnut into shopping list 

### ISSUE THREAD

**Issue by AnkitG-QA** [Poonam123-qa/Java-Practice-Codes#1]
add walnut into shopping list 
![walnuts](https://github.com/user-attachments/assets/859aba00-f4ae-428c-a790-14bcd94f9078)

**Comment by Poonam123-qa** [comment]
Yes receive this defect.

**Comment by AnkitG-QA** [comment]
if it is bug then fixed it

**Comment by Poonam123-qa** [comment]
Yes this bug has been resolved.

**Comment by AnkitG-QA** [comment]
yes bug is closed 
![walnuts](https://github.com/user-attachments/assets/3419c9a7-c2e2-4468-a427-51b125b88677)
